Test of Lazy_matrix_mul module
==========================

Includes the function Lazy_matrix_mul:

	 >>> m = __import__('101-lazy_matrix_mul')
         >>> m.lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
         array([[ 7, 10],
       	 	[15, 22]])
         >>> m.lazy_matrix_mul('hello', [[4, 6, 7], [2, 7, 4]])
         Traceback (most recent call last):
         ValueError: Scalar operands are not allowed, use '*' instead
         >>> m.lazy_matrix_mul([[1, 2], [4, 5]], (4, 6, 2))
         Traceback (most recent call last):
         ValueError: Scalar operands are not allowed, use '*' instead
         >>> m.lazy_matrix_mul([4, 7.4, 2, 6.8], [[4, 6, 7], [2, 7, 4]])
         Traceback (most recent call last):
         ValueError: m_a can only be a matrix
         >>> m.lazy_matrix_mul([[4, 6], [2, 7]], [2, 4,5, 0.8])
         Traceback (most recent call last):
         ValueError: m_b can only be a matrix
         >>> m.lazy_matrix_mul([[]], [[4, 6], [2, 7]])
         Traceback (most recent call last):
         ValueError: m_a cannot be of dimension 0
         >>> m.lazy_matrix_mul([[4, 6], [2, 7]], [])
         Traceback (most recent call last):
         ValueError: m_b cannot be of dimension 0
         >>> m.lazy_matrix_mul([[1, '2'], [3, 4]], [[1, 2], [3, 4]])
         Traceback (most recent call last):
         ValueError: invalid data type for einsum
         >>> m.lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [False, 4]])
         Traceback (most recent call last):
         ValueError: invalid data type for einsum
         >>> m.lazy_matrix_mul([[1, 3, 7.5], [3.5, 7]], [[1, 2], [3, 4]])
         Traceback (most recent call last):
         TypeError: setting an array element with a sequence
         >>> m.lazy_matrix_mul([[1, 7.5], [3.5, 7]], [[1, 2], [3, 5, 4]])
         Traceback (most recent call last):
         TypeError: setting an array element with a sequence
         >>> m.lazy_matrix_mul([[4.7, 3, 6], [1, 8, 3.2]], [[2, 7.1, 4], [1, 22, 3]])
         Traceback (most recent call last):
         ValueError: size of m_a is different than size of m_b
